version: '3'
services:
  backend:
    build: .
    container_name: backend
    profiles: ['project_1']
    networks:
      - test_network

  postgres:
    image: postgres:latest
    container_name: postgres
    profiles: ['project_1']
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - /var/lib/test/nest-test-db:/var/lib/postgresql/data
    networks:
      - test_network

networks:
  test_network:
    external: true
